### ISSUE TITLE
destination creation issue. 

### ISSUE THREAD

**Issue by salamandra2508** [fivetran/terraform-provider-fivetran#131]
`resource "fivetran_group" "test-group" {
    name = "test_dearer"
}

resource "fivetran_destination" "my_test_dest" {
    group_id         = fivetran_group.test-group.id
    region           = "AWS_US_EAST_1"
    service          = "postgres_rds_warehouse"
    time_zone_offset = "-8"
    trust_fingerprints = "true"`

    `config {
        connection_type = "SSHTunnel"
        database        = 
        host            = 
        port            = 
        tunnel_host     = 
        tunnel_port     = 
        tunnel_user     = 
        user            = 
        password        = 
    }
}`

tried to create a destination and all the time get an error -

`Error: create error
with fivetran_destination.my_test_dest
on fivetrans3connector.tf line 29, in resource "fivetran_destination" "my_test_dest":
resource "fivetran_destination" "my_test_dest" {
status code: 400; expected: 201; code: InvalidInput; message: Invalid 'config' object`

**Comment by beevital** [comment]
You can't use `SSHTunnel`, you need `SshTunnel` : https://fivetran.com/docs/rest-api/destinations/config#configparameters_10

The problem is in our API, it doesn't return error details. But in logs we have:
"Cannot deserialize value of type `com.fivetran.core.ConnectionType` from String "SSHTunnel": not one of the values accepted for Enum class: [SshTunnel, PrivateLink, Directly, ProxyAgent]"
