### ISSUE TITLE
Zuora sandbox connector, environment reapplied on every run.

### ISSUE THREAD

**Issue by johnhoran** [fivetran/terraform-provider-fivetran#211]
**Describe the bug**
For zuora sandbox I need to set which environment our credentials authorize us against (choosing between `central sandbox` and `sandbox`).  The setting applies to fivetran initially correctly (without the setting it defaults to sandbox), but then every apply counts as a change.

**To Reproduce**
```hcl
resource "fivetran_connector" "zuora" {
  group_id = var.destination_group.id
  service = coalesce(
    try(yamldecode(data.aws_ssm_parameter.credentials.value).sandbox ? null : "zuora"),
    "zuora_sandbox"
  )

  run_setup_tests = "true"

  destination_schema {
    name = "zuora"
  }

  config {
    client_id     = yamldecode(data.aws_ssm_parameter.credentials.value).client_id
    client_secret = yamldecode(data.aws_ssm_parameter.credentials.value).client_secret
    environment   = try(yamldecode(data.aws_ssm_parameter.credentials.value).environment, null)
  }
}
```
I have a secret in SSM containing 
```yaml
client_id: ...
client_secret: ...
sandbox: true
environment:  Central Sandbox
```

**Logs & Output**
```
  # module.zuora.fivetran_connector.zuora will be updated in-place
  ~ resource "fivetran_connector" "zuora" {
        id              = "predictive_iris"
        name            = "zuora"
        # (6 unchanged attributes hidden)

      ~ config {
          + environment                     = (sensitive value)
            # (49 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 1 to add, 1 to change, 0 to destroy.
```

**Plugin version:**
1.1.0

**Comment by beevital** [comment]
Unfortunately switching between Zuora environments in Fivetran implemented with different service ids.
Service is a "ForceNew" field for connector resource. 
In Fivetrna UI these are two separate services too:
<img width="678" alt="image" src="https://github.com/fivetran/terraform-provider-fivetran/assets/73104048/4a6ac9b2-3ec0-4d8f-ab5b-d23caecf2afe">
And this is a correct behavior from terraform perspective as you literally delete connector of one type and create another connector of different type instead. 
So this is an expected behavior.

**Comment by johnhoran** [comment]
It isn't that I'm switching between zuora and zuora sandbox.  It is always zuora sandbox but I need to specify `Central Sandbox`, vs it's default `Sandbox`.  This sets up correctly but then counts as a change on every apply.
