### ISSUE TITLE
fivetran_connector_schema_config import not working for Snowflake Source

### ISSUE THREAD

**Issue by mcwata7** [fivetran/terraform-provider-fivetran#254]
Terraform version: 1.6.6
Fivetran provider version: 1.1.10

**Describe the bug**
Import using fivetran_connector_schema_config not working. 

> |
> │ Error: Unable to Read Connector Schema Resource.
> │ 
> │ Error wile retrieving existing schema. status code: 404; expected: 200; code: NotFound; message: HTTP 404 Not Found
> |

Using the same connector_id, I'm able to import the fivetran_connector but fails on the schema import.

**Comment by jakerohald** [comment]
@mcwata7 we have faced a similar issue and received the following response from FiveTran: 

_The engineer also let me know that there is no need to import the schema as it is a synthetic resource. The command returns a 404 error because the import operation is not able to reload the schema. The engineer is going to update the documentation to reflect this. As a next step, you can just define the schema in the config without any import._

**Comment by beevital** [comment]
We will remove this part from docs for connector_schema_config resource.
There's no need to import a synthetic resource.
It doesn't create any new entity in upstream, so there can't be any conflict.

**Comment by beevital** [comment]
https://registry.terraform.io/providers/fivetran/fivetran/latest/docs/resources/connector_schema_config#import
