### ISSUE TITLE
feature request: Data Source for Fivetran IP's

### ISSUE THREAD

**Issue by calder-holt** [fivetran/terraform-provider-fivetran#92]
Suggestion to create a Data Source for the Fivetran list of IPs, so it can be used for network policies with Snowflake.

**Comment by beevital** [comment]
You can always use locals in you .tf config and refer to our public docs:
https://fivetran.com/docs/getting-started/ips
We don't think it worth to hardcode it into terraform data-source since something could be changed in our infrastructure and  legacy versions of this data source will became useless.
